package vista;
    import java.text.SimpleDateFormat;
    import modelo.*;
    import javax.swing.table.DefaultTableModel;
    import tda.*;
import javax.swing.JOptionPane;


public class VisualizarDependencia extends javax.swing.JFrame {
   private AdministradorDelSistema adm;
   private DefaultTableModel model;
        
    public VisualizarDependencia(AdministradorDelSistema adm) {
        this.adm = adm;
        initComponents();
        model = new DefaultTableModel();
        model.addColumn("User");
        model.addColumn("ID");
        model.addColumn("Asunto");
        model.addColumn("Prioridad");
        model.addColumn("Tiempo");
        this.jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        main = new javax.swing.JButton();
        dependencia = new javax.swing.JButton();
        expediente = new javax.swing.JButton();
        usuario = new javax.swing.JButton();
        ChauChau = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dependenciaVisualizar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        finalizarAntiguedad = new javax.swing.JButton();
        finalizarPrioridad = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        finalizarID = new javax.swing.JButton();
        IDExp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lmg/Ulima (1).png"))); // NOI18N

        main.setBackground(new java.awt.Color(242, 111, 33));
        main.setForeground(new java.awt.Color(255, 255, 255));
        main.setText("Página de la institución");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });

        dependencia.setForeground(new java.awt.Color(242, 111, 33));
        dependencia.setText("Dependencia");
        dependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dependenciaActionPerformed(evt);
            }
        });

        expediente.setBackground(new java.awt.Color(242, 110, 34));
        expediente.setForeground(new java.awt.Color(255, 255, 255));
        expediente.setText("Expediente");
        expediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expedienteActionPerformed(evt);
            }
        });

        usuario.setBackground(new java.awt.Color(242, 110, 34));
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario");
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        ChauChau.setBackground(new java.awt.Color(242, 110, 34));
        ChauChau.setForeground(new java.awt.Color(255, 255, 255));
        ChauChau.setText("Cerrar sesión");
        ChauChau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChauChauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dependencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(expediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ChauChau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(expediente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ChauChau, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(242, 110, 34));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DEPENDENCIA -> Visualizar dependencia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Ingrese dependencia: ");

        dependenciaVisualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        botonBuscar.setBackground(new java.awt.Color(242, 111, 33));
        botonBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setText("BUSCAR");
        botonBuscar.setToolTipText("");
        botonBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33)));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        finalizarAntiguedad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finalizarAntiguedad.setForeground(new java.awt.Color(242, 111, 33));
        finalizarAntiguedad.setText("Finalizar por antiguedad");
        finalizarAntiguedad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33)));
        finalizarAntiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarAntiguedadActionPerformed(evt);
            }
        });

        finalizarPrioridad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finalizarPrioridad.setForeground(new java.awt.Color(242, 111, 33));
        finalizarPrioridad.setText("Finalizar por prioridad");
        finalizarPrioridad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33)));
        finalizarPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarPrioridadActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33)));

        finalizarID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finalizarID.setForeground(new java.awt.Color(242, 111, 33));
        finalizarID.setText("Finalizar por ID del expediente");
        finalizarID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33), new java.awt.Color(242, 111, 33)));
        finalizarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarIDActionPerformed(evt);
            }
        });

        IDExp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Ingrese el ID:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(finalizarID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDExp, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDExp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(finalizarID, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dependenciaVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(finalizarAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(finalizarPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dependenciaVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(finalizarAntiguedad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finalizarPrioridad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        // ESTE BOTON TE LLEVA AL HOME(PRINCIPAL) DEL SISTEMA
        principal frame = new principal(this.adm);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainActionPerformed

    private void dependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dependenciaActionPerformed
        // ESTE BOTON TE MANDA AL SUB-HOME DE DEPENDENCIA
        DependenciaGUI frame = new DependenciaGUI(this.adm);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dependenciaActionPerformed

    private void expedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expedienteActionPerformed
        // ESTE BOTON TE LLEVA AL SUB-HOME DE EXPEDIENTE
        ExpedienteGUI frame = new ExpedienteGUI(this.adm);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_expedienteActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // ESTE BOTON TE LLEVA A REGISTRAR USUARIO
        UsuarioFont frame = new UsuarioFont(this.adm);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usuarioActionPerformed

    private void ChauChauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChauChauActionPerformed
        // ESTE BOTON CIERRA SESION
        login frame = new login();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChauChauActionPerformed

    private void finalizarPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarPrioridadActionPerformed
        String nomDependencia = this.dependenciaVisualizar.getText(); //obtenemos dependencia escrita en label
        Dependencia actual = this.adm.obtenerDependencia(nomDependencia); //obtenemos dependencia puesta por adm -> de la listaDependencias de la clase AdmDelSistema
        
        if (actual != null) {
            actual.finalizarTramitePrioridad();
            JOptionPane.showMessageDialog(this, "Se ha eliminado expediente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "No existe dependencia", "Error", JOptionPane.ERROR_MESSAGE);
            //ERROR NO EXISTE DEPENDENCIA
        }
        //MENSAJE: SE HA ELIMINADO...
        VisualizarDependencia frame = new VisualizarDependencia(this.adm);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_finalizarPrioridadActionPerformed

    private void finalizarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarIDActionPerformed
        String nomDependencia = this.dependenciaVisualizar.getText(); //obtenemos dependencia escrita en label
        String IDexpediente = this.IDExp.getText(); //obtenemos ID del expediente a finalizar
        
        Dependencia actual = this.adm.obtenerDependencia(nomDependencia); //obtenemos dependencia puesta por adm -> de la listaDependencias de la clase AdmDelSistema
        
        if (actual != null) {
            if (actual.existeTramite(IDexpediente)) {
                actual.finalizarTramiteConID(IDexpediente);
            }
            else{
                JOptionPane.showMessageDialog(this, "No existe expediente", "Error", JOptionPane.ERROR_MESSAGE);
                //ERROR NO EXISTE ESE EXPEDIENTE
            }
        }
        else{
            //ERROR NO EXISTE DEPENDENCIA
            JOptionPane.showMessageDialog(this, "No existe dependencia", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //MENSAJE: SE HA ELIMINADO...
        JOptionPane.showMessageDialog(this, "Se ha eliminado expediente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        VisualizarDependencia frame = new VisualizarDependencia(this.adm);
        frame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_finalizarIDActionPerformed

    private void finalizarAntiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarAntiguedadActionPerformed
        String nomDependencia = this.dependenciaVisualizar.getText(); //obtenemos dependencia escrita en label
        Dependencia actual = this.adm.obtenerDependencia(nomDependencia); //obtenemos dependencia puesta por adm -> de la listaDependencias de la clase AdmDelSistema

        if (actual != null) {
            actual.finalizarTramiteAntiguedad();
            JOptionPane.showMessageDialog(this, "Se ha eliminado expediente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No existe dependencia", "Error", JOptionPane.ERROR_MESSAGE);
        }

        VisualizarDependencia frame = new VisualizarDependencia(this.adm);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_finalizarAntiguedadActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        this.model.setRowCount(0);
        String IDdependenciaABuscar = this.dependenciaVisualizar.getText();
        Dependencia actual = this.adm.obtenerDependencia(IDdependenciaABuscar);
        if (actual != null) {
            actual.verTramitesDepedencia();
        
            String[][] datos = actual.obtenerArrayInfoTramite();
        
            for (String[] dato : datos) {
                model.addRow(dato);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La dependencia ingresada no existe", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VisualizarDependencia().setVisible(true);
            }
        });
    }
    
    public void CargarTabla()
    {
        /*
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String nomDependencia = this.dependenciaVisualizar.getText();
        var actual = this.adm.obtenerDependencia(nomDependencia);
        if (actual != null) {
            var A = actual.getExpedientes();
            var aux = new Cola();
            while(!A.esVacia()){
                var ptr = A.desencolar();
                 model.addRow(new Object[]{
                    ptr.getInteresado().getNombreApellido(),
                    ptr.getAsunto(),
                    String.valueOf(ptr.getPrioridad()),
                    dateFormat.format(ptr.getHoraInicio())
                });
                aux.encolar(ptr);
            }
        }
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChauChau;
    private javax.swing.JTextField IDExp;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton dependencia;
    private javax.swing.JTextField dependenciaVisualizar;
    private javax.swing.JButton expediente;
    private javax.swing.JButton finalizarAntiguedad;
    private javax.swing.JButton finalizarID;
    private javax.swing.JButton finalizarPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton main;
    private javax.swing.JButton usuario;
    // End of variables declaration//GEN-END:variables
}
